apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus_main
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      timeInterval: "15s"
      queryTimeout: "60s"
